package com.bit_trade.web.enums;

public enum Action {
	MOVE,REGISTER,ACCESS,
	SIGNUP,SIGNIN,
	CUST_LIST,CUST_PHONE,CUST_RETRIEVE,CUST_UPDATE, CUST_FILE_UPLOAD, CUST_DELETE, PRODUCT_LIST, 
	CATE_LIST
	;
}


